# -*- coding: utf-8 -*-
"""CollectionPython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzngrVrZIdalxAN5MfrETDZNGmniOI3f

## Container
collection is a container that holds multiple items, it could be ant type like list (ordered), tuples immutable, set like a bag, dictionarires key value pair. Supports json

## Collection: Tuples
ordered and immutable, allow duplicate

example: create employee tuple which represent a role in employee table
"""

employee = (1, 'Canada', 'Ontaria', 965858545455)
print(employee)

print(employee[1]) # Print

print(len(employee)) # len of the tuple

print(employee[-1])

# Tuples are immutable. You can convert them to a list first before you make the mutable
# and convert the list into a tuple to make the change
employee = (1, 'Canada', 'Ontaria', 965858545455)
new_emp = list(employee)
new_emp[1] = "Canada my home country"
employee = tuple(new_emp)
print(employee)

# You can iterate on a tuple using a for loop
for x in employee:
  print(x)

# you can find the index of the tuple using
print(employee.index('Ontaria'))

"""1. You have learnt about tuples
2. how to update
3. How to iterate
4. and how to use tuple

## List
Used to store multtiple variable. list are:
1. mutable
2. Ordered
3. Allow duplicate values
"""

# Example
tasks = ['Development', 'testing', 'monitoring']
print(tasks, "\n")
for x in tasks:
  print(x)

# to access a particular element, you use indexing
print(tasks[1])



# Assigning an item
tasks[1] = "New_string"
print(tasks)

# Append
tasks.append('Production deployment')
print(tasks)

# Insert
tasks.insert(1, "unity testing")
print(tasks)

# Remove through items
tasks.remove('unity testing')
print(tasks)

# Remove through indexing
tasks.pop(1)
print(tasks)

# iterate
for x in tasks:
  print(x)

"""# Sets
Unique piece
Sets don't have an order
"""

tasks = {'development', 'testing', 'monitoring'}
print(tasks)

tasks = {'development', 'testing', 'monitoring', 'testing'}
print(tasks)

# Add
tasks.add('prod development')
print(tasks)

next_tasks = {'unit testing', 'SIT testing'}
tasks.update(next_tasks)
print(tasks)

# Remove sets
tasks.remove('testing')
print(tasks)

# To clear sets
tasks.clear()
print(tasks)

"""In sets, you can perform union, join, intersection.

## Dictionary
1. Ordered
2. Mutable
3. No duplicates
"""

user  = {'name': "Paul", 'city': 'London', 'Age': 20}
print(user)

print(user['city'])

user.get('city')

keys = user.keys()
print(keys)

values = user.values()
print(values)

# To find if a particular key exist or not
if 'name' in user:
  print('yes')

# Replacing a value
user['city'] = 'Toronto'
print(user)

# Add a new dictionary
user.update({'mobile': 3252564510})
print(user)

user.pop('mobile')

for x in user.keys():
  print(user[x])

new_user = user
new_user.update({'mobile': 2150254568})
print(new_user)

new_user = user.copy()

