# -*- coding: utf-8 -*-
"""ErrorHandling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aiFraDzKSb7vgx86x0nEN7LFW9QQ7ae-
"""

print(10/0)

try:
  print(10/0)
except ZeroDivisionError:
  print("You're dividing by zero")

"""If you don't know the kind of errror"""

try:
  print(10/0)
except:
  print("You're dividing by zero")

try:
  print(10/2)
except:
  print("You're dividing by zero")
else:
  print("Nothing is wrong with the code")

try:
  print(10/2)
except:
  print("You're dividing by zero")
else:
  print("Nothing is wrong with the code")
finally:
  print("Execute always")

"""This is useful when you perform file rewrite"""