# -*- coding: utf-8 -*-
"""FindSmallestNo0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vy6XVEFy9Aalk8fLnRbYGKyXv5ymriYY
"""

# find the smallest number in a list.
# You're given an a list of integer
# Your task: Return the smallest number in the list using a built-in function

def find_smallest_number(numbers):
  return min(numbers)

# Test
list_num = [2, 1, 65, 59, 25]
find_smallest_number(list_num)