# -*- coding: utf-8 -*-
"""PythonDataType.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rRMhTOC71JPaNJvrd_HVcub8OKMTTdz
"""

print("Hello, Data engineer!")

"""## Python Datatype and Variables
Variable is a container that stores a value


"""

greeting = "Hello, Data Engineer"
print(greeting)

"""Datatype: Integer, string, float and boolean"""

int_var = 7
float_var = 3.12
str_var = "Hello world"
bol_var = True

print(int_var)

"""Functions: Reuseanle code block
Modularise the code
Helps in managing the large code
"""

